name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }} # 确保只在 Fork 的仓库中运行

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v6

      - name: Sync upstream changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh repo sync ${{ github.repository }} -s NodeSeekDev/NodeGet-board
